source "https://rubygems.org"

group :jekyll_plugins do
  gem 'jekyll-watch', :git => "https://github.com/CloudCannon/jekyll-watch"
  gem 'jekyll-include-cache'
  gem 'jekyll-local-assign'
end

gem 'jekyll-sitemap'
gem 'bundler-audit', require: false